/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "/data/codes/queryphp.com/node_modules/@vuepress/core/lib/app/root-mixins/updateMeta.js"
import m1 from "/data/codes/queryphp.com/node_modules/@vuepress/plugin-active-header-links/mixin.js"
import m2 from "/data/codes/queryphp.com/docs/.vuepress/mixin.js"

export default [
  m0,
  m1,
  m2
]