/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption } from '@app/util'
import rootMixins from '@internal/root-mixins'
import components from '@internal/layout-components'
import LayoutDistributor from '@app/components/LayoutDistributor.vue'

injectComponentOption(LayoutDistributor, 'mixins', rootMixins)
injectComponentOption(LayoutDistributor, 'components', components)
export const routes = [
  {
    name: "v-1513872612b63",
    path: "/about/",
    component: LayoutDistributor,
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-49ff78160ab3c",
    path: "/ecosystem/",
    component: LayoutDistributor,
  },
  {
    path: "/ecosystem/index.html",
    redirect: "/ecosystem/"
  },
  {
    name: "v-b2a4367f77395",
    path: "/en/faq/",
    component: LayoutDistributor,
  },
  {
    path: "/en/faq/index.html",
    redirect: "/en/faq/"
  },
  {
    name: "v-f26fb2c5c8cc8",
    path: "/en/guide/",
    component: LayoutDistributor,
  },
  {
    path: "/en/guide/index.html",
    redirect: "/en/guide/"
  },
  {
    name: "v-e77a0c68066ea",
    path: "/en/",
    component: LayoutDistributor,
  },
  {
    path: "/en/index.html",
    redirect: "/en/"
  },
  {
    name: "v-c78db110cec38",
    path: "/en/guide/assets.html",
    component: LayoutDistributor,
  },
  {
    name: "v-2321c9cfa15c9",
    path: "/en/guide/deploy.html",
    component: LayoutDistributor,
  },
  {
    name: "v-3a79b87658559",
    path: "/en/guide/directory-structure.html",
    component: LayoutDistributor,
  },
  {
    name: "v-46e47f2f45926",
    path: "/en/guide/basic-config.html",
    component: LayoutDistributor,
  },
  {
    name: "v-778d5ae25d8f7",
    path: "/en/guide/markdown.html",
    component: LayoutDistributor,
  },
  {
    name: "v-5aed5b24ccb7",
    path: "/en/guide/i18n.html",
    component: LayoutDistributor,
  },
  {
    name: "v-71ba02c1f0ed6",
    path: "/en/guide/getting-started.html",
    component: LayoutDistributor,
  },
  {
    name: "v-83bc0d504abb5",
    path: "/en/guide/permalinks.html",
    component: LayoutDistributor,
  },
  {
    name: "v-e2fd4a5a2a784",
    path: "/en/guide/using-vue.html",
    component: LayoutDistributor,
  },
  {
    name: "v-638ce8013a5f3",
    path: "/en/miscellaneous/design-concepts.html",
    component: LayoutDistributor,
  },
  {
    name: "v-632e2b9f3a01b",
    path: "/en/miscellaneous/migration-guide.html",
    component: LayoutDistributor,
  },
  {
    name: "v-6252f9c13f971",
    path: "/en/miscellaneous/global-computed.html",
    component: LayoutDistributor,
  },
  {
    name: "v-774ff116be765",
    path: "/en/miscellaneous/glossary.html",
    component: LayoutDistributor,
  },
  {
    name: "v-ce23fe7d5b59b",
    path: "/en/plugin/official.html",
    component: LayoutDistributor,
  },
  {
    name: "v-f0452c2c2d62a",
    path: "/en/theme/",
    component: LayoutDistributor,
  },
  {
    path: "/en/theme/index.html",
    redirect: "/en/theme/"
  },
  {
    name: "v-00a4173f1471",
    path: "/guide/",
    component: LayoutDistributor,
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-6d7a3d9eb07e7",
    path: "/faq/",
    component: LayoutDistributor,
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-981541f88b45c",
    path: "/guide/assets.html",
    component: LayoutDistributor,
  },
  {
    name: "v-694695a4614ad",
    path: "/guide/basic-config.html",
    component: LayoutDistributor,
  },
  {
    name: "v-d3ff1e906f21e",
    path: "/guide/getting-started.html",
    component: LayoutDistributor,
  },
  {
    name: "v-b3dcb4aeb07f1",
    path: "/guide/deploy.html",
    component: LayoutDistributor,
  },
  {
    name: "v-b691a7c4fd32b",
    path: "/guide/custom-themes.html",
    component: LayoutDistributor,
  },
  {
    name: "v-39712643467e4",
    path: "/guide/directory-structure.html",
    component: LayoutDistributor,
  },
  {
    name: "v-c444fcb7a40dd",
    path: "/guide/i18n.html",
    component: LayoutDistributor,
  },
  {
    name: "v-0c155dcb0f206",
    path: "/guide/markdown.html",
    component: LayoutDistributor,
  },
  {
    name: "v-3145ba0a3db91",
    path: "/guide/permalinks.html",
    component: LayoutDistributor,
  },
  {
    name: "v-f886f7a845894",
    path: "/guide/using-vue.html",
    component: LayoutDistributor,
  },
  {
    name: "v-6c84eacd7b8d7",
    path: "/miscellaneous/design-concepts.html",
    component: LayoutDistributor,
  },
  {
    name: "v-2e263271d64ce",
    path: "/miscellaneous/global-computed.html",
    component: LayoutDistributor,
  },
  {
    name: "v-c6d8e7f468454",
    path: "/miscellaneous/glossary.html",
    component: LayoutDistributor,
  },
  {
    name: "v-aaa5a7d3c5f94",
    path: "/miscellaneous/migration-guide.html",
    component: LayoutDistributor,
  },
  {
    name: "v-dc077666a8c03",
    path: "/plugin/official.html",
    component: LayoutDistributor,
  },
  {
    name: "v-1b8f0b5508ab8",
    path: "/theme/",
    component: LayoutDistributor,
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-590a2daee1e3e",
    path: "/config/",
    component: LayoutDistributor,
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-e0568791ba7e1",
    path: "/en/config/",
    component: LayoutDistributor,
  },
  {
    path: "/en/config/index.html",
    redirect: "/en/config/"
  },
  {
    name: "v-edf88401f440d",
    path: "/en/plugin/",
    component: LayoutDistributor,
  },
  {
    path: "/en/plugin/index.html",
    redirect: "/en/plugin/"
  },
  {
    name: "v-12495ce87d355",
    path: "/en/theme/default-theme-config.html",
    component: LayoutDistributor,
  },
  {
    name: "v-53b7c91f6b8f",
    path: "/plugin/",
    component: LayoutDistributor,
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-50aa8e52aa369",
    path: "/theme/default-theme-config.html",
    component: LayoutDistributor,
  },
  {
    name: "v-e46a0188abdf1",
    path: "/",
    component: LayoutDistributor,
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: LayoutDistributor
  }
]